This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file C:/Users/swchoi/Desktop/thesis/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main.acn....done (181 entries accepted, 0 rejected).
Sorting entries.....done (1638 comparisons).
Generating output file main.acr....done (68 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
